server {
    listen 8080;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This line is magic: It ensures React Router doesn't show 404 errors!
        try_files $uri $uri/ /index.html; 
    }
}